import { pgTable, text, integer, boolean, date, timestamp, jsonb } from "drizzle-orm/pg-core";

export const followUpTasks = pgTable("follow_up_tasks", {
  task_id: text("task_id").primaryKey(),
  task_key: text("task_key").notNull().unique(),
  site_id: integer("site_id").notNull(),
  locality_code: text("locality_code").notNull(),
  household_id: text("household_id"),
  subject_type: text("subject_type").notNull(),
  subject_id: text("subject_id").notNull(),
  woman_id: text("woman_id"),
  pregnancy_id: text("pregnancy_id"),
  child_id: text("child_id"),
  task_type: text("task_type").notNull(),
  form_code: text("form_code"),
  expected_forms: text("expected_forms").array(),
  series_id: text("series_id"),
  sequence_number: integer("sequence_number"),
  protocol_visit_label: text("protocol_visit_label"),
  generation_source: text("generation_source").notNull(),
  source_event_id: text("source_event_id"),
  anchor_event_id: text("anchor_event_id"),
  anchor_date: date("anchor_date"),
  window_start: date("window_start"),
  target_date: date("target_date").notNull(),
  deadline_date: date("deadline_date"),
  status: text("status").default("planned"),
  priority: integer("priority").default(0),
  default_expected_mode: text("default_expected_mode"),
  allowed_modes: text("allowed_modes").array(),
  mode_rule_strength: text("mode_rule_strength"),
  max_failed_attempts: integer("max_failed_attempts"),
  failed_attempt_count: integer("failed_attempt_count").default(0),
  requires_final_close_reason: boolean("requires_final_close_reason").default(false),
  task_context_json: jsonb("task_context_json"),
  context_builder_version: text("context_builder_version"),
  prefill_mapper_version: text("prefill_mapper_version"),
  rules_version: text("rules_version"),
  form_availability: text("form_availability").default("available"),
  action_state: text("action_state").default("enabled"),
  disabled_reason: text("disabled_reason"),
  completed_visit_id: text("completed_visit_id"),
  completed_at: timestamp("completed_at", { withTimezone: true }),
  closed_at: timestamp("closed_at", { withTimezone: true }),
  closed_reason: text("closed_reason"),
  superseded_by_event_id: text("superseded_by_event_id"),
  created_at: timestamp("created_at", { withTimezone: true }),
  updated_at: timestamp("updated_at", { withTimezone: true }),
});

export const taskAttempts = pgTable("task_attempts", {
  attempt_id: text("attempt_id").primaryKey(),
  task_id: text("task_id").notNull(),
  attempt_number: integer("attempt_number").notNull(),
  visit_id: text("visit_id"),
  attempted_at: timestamp("attempted_at", { withTimezone: true }).notNull(),
  attempted_by_user_id: text("attempted_by_user_id"),
  device_id: text("device_id"),
  attempted_mode: text("attempted_mode"),
  outcome: text("outcome").notNull(),
  reason_code: text("reason_code"),
  notes: text("notes"),
  next_attempt_date: date("next_attempt_date"),
  created_at: timestamp("created_at", { withTimezone: true }),
});
