import { pgTable, text, integer, timestamp, jsonb } from "drizzle-orm/pg-core";

export const visits = pgTable("visits", {
  visit_id: text("visit_id").primaryKey(),
  session_id: text("session_id"),
  site_id: integer("site_id").notNull(),
  locality_code: text("locality_code").notNull(),
  household_id: text("household_id").notNull(),
  primary_subject_type: text("primary_subject_type"),
  primary_subject_id: text("primary_subject_id"),
  started_at: timestamp("started_at", { withTimezone: true }),
  completed_at: timestamp("completed_at", { withTimezone: true }),
  interviewer_id: text("interviewer_id"),
  device_id: text("device_id"),
  actual_mode: text("actual_mode"),
  gps_metadata: jsonb("gps_metadata"),
  sync_status: text("sync_status").default("local"),
  created_at: timestamp("created_at", { withTimezone: true }),
});

export const formResponses = pgTable("form_responses", {
  form_response_id: text("form_response_id").primaryKey(),
  response_id: text("response_id").notNull().unique(),
  site_id: integer("site_id").notNull(),
  locality_code: text("locality_code").notNull(),
  household_id: text("household_id"),
  visit_id: text("visit_id").references(() => visits.visit_id),
  task_id: text("task_id"),
  series_id: text("series_id"),
  sequence_number: integer("sequence_number"),
  form_code: text("form_code").notNull(),
  form_version: text("form_version").notNull(),
  subject_type: text("subject_type"),
  subject_id: text("subject_id"),
  lineage_ids_json: jsonb("lineage_ids_json"),
  prefill_snapshot_json: jsonb("prefill_snapshot_json"),
  prefill_mapper_version: text("prefill_mapper_version"),
  answers_json: jsonb("answers_json").notNull(),
  created_offline_at: timestamp("created_offline_at", { withTimezone: true }),
  updated_offline_at: timestamp("updated_offline_at", { withTimezone: true }),
  device_id: text("device_id"),
  synced_at: timestamp("synced_at", { withTimezone: true }),
  response_status: text("response_status").default("primary"),
  created_at: timestamp("created_at", { withTimezone: true }),
});
