/**
 * Expo config plugin: withAndroidReleaseSigning
 *
 * Local dev / default CI (no env vars set): pure no-op, the generated
 * android/app/build.gradle keeps signing its "release" buildType with the
 * bundled debug keystore, exactly as `expo prebuild` produces it out of the box.
 *
 * CI release builds (env vars set): reads the following environment
 * variables at `expo prebuild` time and, if ALL four signing vars are
 * present, adds a `release` signingConfig (backed by gradle.properties
 * entries so no secret ever lands in build.gradle itself) and switches the
 * `release` buildType to use it instead of the debug keystore:
 *
 *   ANDROID_RELEASE_KEYSTORE_PATH
 *   ANDROID_RELEASE_KEYSTORE_PASSWORD
 *   ANDROID_RELEASE_KEY_ALIAS
 *   ANDROID_RELEASE_KEY_PASSWORD
 *
 * Independently, if set, the following env vars are applied to the Expo
 * config itself (before Expo's own built-in Android base mods run), which
 * is how versionCode / versionName end up in the generated build.gradle:
 *
 *   ANDROID_VERSION_NAME   -> config.version           (-> android versionName)
 *   ANDROID_VERSION_CODE   -> config.android.versionCode (-> android versionCode)
 */

const { withAppBuildGradle, withGradleProperties } = require("@expo/config-plugins");

const SIGNING_BLOCK_START = "        // BEGIN dynamic-release-signing (generated by withAndroidReleaseSigning)";
const SIGNING_BLOCK_END = "        // END dynamic-release-signing";

const GRADLE_PROPERTY_KEYS = {
  storeFile: "DYNAMIC_RELEASE_STORE_FILE",
  storePassword: "DYNAMIC_RELEASE_STORE_PASSWORD",
  keyAlias: "DYNAMIC_RELEASE_KEY_ALIAS",
  keyPassword: "DYNAMIC_RELEASE_KEY_PASSWORD",
};

const SIGNING_CONFIGS_OPEN_REGEX = /(signingConfigs\s*\{\n)/;

// Matches `signingConfig signingConfigs.debug` only when it appears inside the
// `release { ... }` buildType block (non-greedy match bounded by the block's
// own closing brace, which is safe because the generated `release {}` block
// does not itself contain nested `{}` blocks).
const RELEASE_BUILD_TYPE_DEBUG_SIGNING_REGEX = /(release\s*\{[^}]*?signingConfig\s+signingConfigs\.)debug\b/;

function buildReleaseSigningConfigBlock() {
  return (
    `${SIGNING_BLOCK_START}\n` +
    `        release {\n` +
    `            storeFile file(${GRADLE_PROPERTY_KEYS.storeFile})\n` +
    `            storePassword ${GRADLE_PROPERTY_KEYS.storePassword}\n` +
    `            keyAlias ${GRADLE_PROPERTY_KEYS.keyAlias}\n` +
    `            keyPassword ${GRADLE_PROPERTY_KEYS.keyPassword}\n` +
    `        }\n` +
    `${SIGNING_BLOCK_END}\n`
  );
}

function switchReleaseBuildTypeToReleaseSigning(gradleSource) {
  return gradleSource.replace(RELEASE_BUILD_TYPE_DEBUG_SIGNING_REGEX, "$1release");
}

/**
 * Pure string transformation, exported for unit testing.
 *
 * Given the contents of a generated android/app/build.gradle, inserts a
 * `release` signingConfig (reading from gradle.properties) into the
 * `signingConfigs {}` block, and points the `release` buildType at it
 * instead of `signingConfigs.debug`. Idempotent: calling it again on
 * already-transformed source makes no further changes.
 */
function applyReleaseSigningToBuildGradle(gradleSource) {
  let updated = gradleSource;

  if (!updated.includes(SIGNING_BLOCK_START)) {
    if (!SIGNING_CONFIGS_OPEN_REGEX.test(updated)) {
      // Unexpected build.gradle shape (no signingConfigs block) — leave untouched.
      return updated;
    }
    updated = updated.replace(SIGNING_CONFIGS_OPEN_REGEX, `$1${buildReleaseSigningConfigBlock()}`);
  }

  updated = switchReleaseBuildTypeToReleaseSigning(updated);

  return updated;
}

function setGradleProperty(items, key, value) {
  const existingIndex = items.findIndex((item) => item.type === "property" && item.key === key);
  const nextItem = { type: "property", key, value: String(value) };

  if (existingIndex >= 0) {
    const next = items.slice();
    next[existingIndex] = nextItem;
    return next;
  }

  return [...items, nextItem];
}

// Gradle JVM heap for the generated android/ project. Expo's default
// (-Xmx2048m) is too small for D8 dex merging of this app's dependency set
// in release builds ("java.lang.OutOfMemoryError: Java heap space" on the
// 16 GB GitHub runner), so raise it for every prebuild, CI or local.
const GRADLE_JVM_ARGS = "-Xmx4096m -XX:MaxMetaspaceSize=1024m";

function applyGradleJvmArgs(items) {
  return setGradleProperty(items, "org.gradle.jvmargs", GRADLE_JVM_ARGS);
}

function withAndroidReleaseSigning(config) {
  const {
    ANDROID_RELEASE_KEYSTORE_PATH,
    ANDROID_RELEASE_KEYSTORE_PASSWORD,
    ANDROID_RELEASE_KEY_ALIAS,
    ANDROID_RELEASE_KEY_PASSWORD,
    ANDROID_VERSION_NAME,
    ANDROID_VERSION_CODE,
  } = process.env;

  // Applied directly on the config object (not inside a mod callback) so the
  // mutation is visible to Expo's own built-in Android base mods (which set
  // android:versionCode / versionName from config.android.versionCode /
  // config.version) later in the same prebuild pass.
  if (ANDROID_VERSION_NAME) {
    config.version = ANDROID_VERSION_NAME;
  }
  if (ANDROID_VERSION_CODE) {
    const parsedVersionCode = parseInt(ANDROID_VERSION_CODE, 10);
    if (!Number.isNaN(parsedVersionCode)) {
      config.android = config.android || {};
      config.android.versionCode = parsedVersionCode;
    }
  }

  const hasReleaseSigningEnv =
    Boolean(ANDROID_RELEASE_KEYSTORE_PATH) &&
    Boolean(ANDROID_RELEASE_KEYSTORE_PASSWORD) &&
    Boolean(ANDROID_RELEASE_KEY_ALIAS) &&
    Boolean(ANDROID_RELEASE_KEY_PASSWORD);

  config = withGradleProperties(config, (config) => {
    config.modResults = applyGradleJvmArgs(config.modResults);
    return config;
  });

  if (!hasReleaseSigningEnv) {
    // Signing is a no-op: local dev / any build without release signing
    // secrets keeps the default debug-signed release buildType that
    // `expo prebuild` generates. (The JVM heap setting above still applies.)
    return config;
  }

  config = withGradleProperties(config, (config) => {
    config.modResults = setGradleProperty(
      config.modResults,
      GRADLE_PROPERTY_KEYS.storeFile,
      ANDROID_RELEASE_KEYSTORE_PATH
    );
    config.modResults = setGradleProperty(
      config.modResults,
      GRADLE_PROPERTY_KEYS.storePassword,
      ANDROID_RELEASE_KEYSTORE_PASSWORD
    );
    config.modResults = setGradleProperty(
      config.modResults,
      GRADLE_PROPERTY_KEYS.keyAlias,
      ANDROID_RELEASE_KEY_ALIAS
    );
    config.modResults = setGradleProperty(
      config.modResults,
      GRADLE_PROPERTY_KEYS.keyPassword,
      ANDROID_RELEASE_KEY_PASSWORD
    );
    return config;
  });

  config = withAppBuildGradle(config, (config) => {
    if (config.modResults.language === "groovy") {
      config.modResults.contents = applyReleaseSigningToBuildGradle(config.modResults.contents);
    }
    return config;
  });

  return config;
}

module.exports = withAndroidReleaseSigning;
module.exports.applyReleaseSigningToBuildGradle = applyReleaseSigningToBuildGradle;
module.exports.applyGradleJvmArgs = applyGradleJvmArgs;
module.exports.GRADLE_JVM_ARGS = GRADLE_JVM_ARGS;
